name: ColorPalette
main: pl.semimc.colorpalette.ColorPalettePlugin
version: 1.0
api-version: 1.20
author: kznlabs
description: Plugin do wyboru palety kolorów przez gracza z obsługą PlaceholderAPI i MariaDB.
depend: [PlaceholderAPI]
commands:
  colorpalette:
    description: Pozwala na zmiane palety kolorów gracza
    permission: colorpalette
    aliases: [paleta]
permissions:
  colorpalette.reload:
    description: Pozwala na przeładowanie pluginu ColorPalette
    default: op
